### ISSUE TITLE
SaltRenderError in bind_local_config

### ISSUE THREAD

**Issue by mjinks** [saltstack-formulas/bind-formula#50]
I started out thinking that this was something I was doing wrong, and I'm still not sure it isn't, but after backing out all the relevant stuff I've done I still get the same error: the 'bind_local_config' state won't render, with a Jinja complaint,

`SaltRenderError: Jinja variable 'dict object' has no attribute 'notify'`

...and that still happens even if I take every reference to 'notify' out of my pillar.

Help.

Writeup I posted on gist:
 
  https://gist.github.com/mjinks/cfefc0c50a5a6dd3f5d4

Full text of the error I'm hitting:

    ID: bind_local_config
    
    Function: file.managed

        Name: /etc/bind/named.conf.local
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1423, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3142, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 2841, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 121, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 324, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'dict object' has no attribute 'notify'
     Started: 19:38:23.729014
    Duration: 68.164 ms
     Changes:

**Comment by mjinks** [comment]
Garm. Auto-formatting of that Gist link made a 404 (I probably didn't grasp how to auto-link here) but changing it back to bare text fixes it.

  https://gist.github.com/mjinks/cfefc0c50a5a6dd3f5d4

**Comment by mjinks** [comment]
Yep, it was my fault: if an entry in the pillar under 'configured_zones' doesn't have a 'notify:' item (True or False), the pillar format crashes.

At least, here, once I add that item to the entry that didn't have it, the error goes away.
